import { expect, test, type Page } from '@playwright/test'
async function writeOne(page: Page) {
  const box = await page.getByLabel('Writing surface').boundingBox()
  if (!box) throw new Error('Writing square unavailable')
  const points = [[0.101, 0.498], [0.3, 0.49], [0.5, 0.475], [0.7, 0.465], [0.89, 0.459]] as const
  await page.mouse.move(box.x + points[0][0] * box.width, box.y + points[0][1] * box.height)
  await page.mouse.down()
  for (const point of points.slice(1)) await page.mouse.move(box.x + point[0] * box.width, box.y + point[1] * box.height, { steps: 5 })
  await page.mouse.up()
}
async function writeBackwards(page: Page) {
  const box = await page.getByLabel('Writing surface').boundingBox()
  if (!box) throw new Error('Writing square unavailable')
  await page.mouse.move(box.x + box.width * 0.89, box.y + box.height * 0.46)
  await page.mouse.down()
  await page.mouse.move(box.x + box.width * 0.1, box.y + box.height * 0.5, { steps: 20 })
  await page.mouse.up()
}

test('guide fades under ink and disappears in recall; completed steps survive reload', async ({ page }) => {
  await page.goto('/#/')
  await expect(page.getByRole('heading', { name: 'Remember by writing.' })).toBeVisible()
  await page.getByLabel('New cards').selectOption('5')
  await page.getByRole('button', { name: 'Start session' }).click()
  await expect(page.getByText('Learning · trace')).toBeVisible()
  await expect(page.locator('.session-guide')).toBeVisible()
  expect(await page.locator('.session-guide').evaluate((svg) => Number(getComputedStyle(svg).opacity))).toBeGreaterThan(0.3)
  await writeOne(page)
  const check = page.locator('.session-actions').getByRole('button', { name: 'Check' })
  const checkBox = await check.boundingBox()
  if (!checkBox) throw new Error('Check button unavailable')
  const scrollBefore = await page.evaluate(() => window.scrollY)
  await check.click()
  await expect(page.getByText('Match saved')).toBeVisible()
  const continueButton = page.locator('.session-actions').getByRole('button', { name: 'Continue' })
  const continueBox = await continueButton.boundingBox()
  if (!continueBox) throw new Error('Continue button unavailable')
  const scrollAfter = await page.evaluate(() => window.scrollY)
  expect(Math.abs(continueBox.y + scrollAfter - checkBox.y - scrollBefore)).toBeLessThan(1)
  expect(Math.abs(continueBox.x + continueBox.width - checkBox.x - checkBox.width)).toBeLessThan(1)
  await expect(page.getByRole('button', { name: 'Check' })).toHaveCount(0)
  await page.reload()
  await expect(page.getByText('Match saved')).toBeVisible()
  await page.getByRole('button', { name: 'Continue' }).click()
  await expect(page.getByText('Learning · copy')).toBeVisible()
  expect(await page.locator('.session-guide').evaluate((svg) => Number(getComputedStyle(svg).opacity))).toBeLessThan(0.2)
  await writeOne(page)
  await page.getByRole('button', { name: 'Check' }).click()
  await page.getByRole('button', { name: 'Continue' }).click()
  await expect(page.getByText('Learning · recall')).toBeVisible()
  await expect(page.locator('.session-guide')).toHaveCount(0)
  await expect(page.locator('.session-screen')).not.toContainText('一')
})

test('failed learning steps return to the trace guide without advancing the queue', async ({ page }) => {
  await page.goto('/#/')
  await page.getByLabel('New cards').selectOption('5')
  await page.getByRole('button', { name: 'Start session' }).click()
  await writeBackwards(page)
  await page.getByRole('button', { name: 'Check' }).click()
  await expect(page.getByText('Needs another try · saved')).toBeVisible()
  await page.getByRole('button', { name: 'Continue' }).click()
  await expect(page.getByText('Learning · trace')).toBeVisible()
  await expect(page.getByText('Ready to write')).toBeVisible()
  await expect(page.getByText('Card 1 of 5')).toBeVisible()
  await writeOne(page)
  await page.getByRole('button', { name: 'Check' }).click()
  await page.getByRole('button', { name: 'Continue' }).click()
  await expect(page.getByText('Learning · copy')).toBeVisible()
  await writeBackwards(page)
  await page.getByRole('button', { name: 'Check' }).click()
  await page.getByRole('button', { name: 'Continue' }).click()
  await expect(page.getByText('Learning · trace')).toBeVisible()
})
