import { createHash } from 'node:crypto'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { URL } from 'node:url'
import { svgPathProperties } from 'svg-path-properties'

const source = new URL('../data/sources/kanjivg/05341.svg', import.meta.url)
const destination = new URL('../src/data/generated/ten.ts', import.meta.url)
const expectedSha256 = '3a949bec637d519d51c89d2720cc4db11d7e645f4573b93aee8ecf0e316e9daa'
const xml = await readFile(source, 'utf8')
const sha256 = createHash('sha256').update(xml).digest('hex')
if (sha256 !== expectedSha256) throw new Error('Pinned KanjiVG source hash changed')

const group = xml.match(/<g id="kvg:StrokePaths_05341"[^>]*>([\s\S]*?)<\/g>/)
if (!group) throw new Error('StrokePaths group missing')
const paths = [...group[1].matchAll(/<path id="kvg:05341-s(\d+)"[^>]*\bd="([^"]+)"\s*\/>/g)]
if (paths.length !== 2) throw new Error('Expected exactly two canonical paths')
const strokes = paths.map((path, index) => {
  if (Number(path[1]) !== index + 1) throw new Error('Non-contiguous stroke IDs')
  const d = path[2]
  const geometry = new svgPathProperties(d)
  const originalLength = geometry.getTotalLength()
  const samples = Array.from({ length: 64 }, (_, sampleIndex) => {
    const point = geometry.getPointAtLength(originalLength * sampleIndex / 63)
    return { x: Number((point.x / 109).toFixed(6)), y: Number((point.y / 109).toFixed(6)) }
  })
  if (!Number.isFinite(originalLength) || samples.some((point) => !Number.isFinite(point.x) || !Number.isFinite(point.y))) {
    throw new Error('Nonfinite path geometry')
  }
  return { index, pathD: d, samples, length: Number((originalLength / 109).toFixed(6)) }
})

const definition = {
  id: 'u5341',
  cardId: 'writing:u5341:v1',
  character: '十',
  promptMeaning: 'ten',
  readings: [{ kana: 'じゅう', kind: 'on', showInPrompt: true }],
  viewBox: [0, 0, 109, 109],
  strokeCount: 2,
  strokes,
  datasetVersion: 'm1-ten-1',
  provenanceId: 'kanjivg-05341-422b5538',
}
await mkdir(new URL('../src/data/generated/', import.meta.url), { recursive: true })
await writeFile(destination, `// Generated by scripts/generate-ten.mjs from the pinned KanjiVG SVG.\n// Derived stroke geometry: CC BY-SA 3.0; see data/sources/kanjivg/NOTICE.md.\nexport const tenDefinition = ${JSON.stringify(definition, null, 2)} as const\n`)
